// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pxneryedanrxbajbmcfh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB4bmVyeWVkYW5yeGJhamJtY2ZoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI5NDAzMzUsImV4cCI6MjA2ODUxNjMzNX0.nA-pLLelGp8ALlaXl76Umk4so4kUYRKAdXV38whKkso";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});